# Generated by Django 4.1.7 on 2023-03-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeAds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('currency', models.CharField(max_length=4)),
                ('square_price', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=50)),
                ('floor', models.CharField(max_length=10)),
                ('area', models.CharField(max_length=50)),
                ('rooms', models.CharField(max_length=50)),
                ('title_deed', models.BooleanField(blank=True, default=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='OnSaleHouse',
        ),
        migrations.DeleteModel(
            name='RentalHouse',
        ),
    ]
