# Generated by Django 4.1.7 on 2023-03-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_remove_homeads_title_deed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeads',
            name='price',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='homeads',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
