# Generated by Django 4.1.7 on 2023-03-16 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_alter_homeads_price_alter_homeads_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeads',
            name='no',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homeads',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
