# Generated by Django 4.1.7 on 2023-03-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_homeads_no_alter_homeads_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeads',
            name='square_price',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
