# Generated by Django 4.1.7 on 2023-03-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_alter_homeads_square_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeads',
            name='image_url',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
